### ISSUE TITLE
automagically pull in readme.md from action

### ISSUE THREAD

**Issue by maxheld83** [boyney123/github-actions#20]
would be really cool if the website could automatically pull in the content of some actions `README.md`, instead of pasting it manually.
Especially because in these early days, `README.md`s are probably going to change a lot and frequently.

**Comment by boyney123** [comment]
Hey @maxheld83 

Yeah its on my list of things to do, wanted to get something up and running.

I have spiked out a script that calls Github API's to get details from it, working well. I can get tags, releases etc, all sorts. So I'm going to update the site soon and workflow

**Comment by boyney123** [comment]
Hey @maxheld83 

So I set something up:

https://github-actions.netlify.com/.netlify/functions/github?url=https://github.com/shalzz/zola-deploy-action

Its a function that given a url will return the markdown required to add an action to the website. I will automate a few bits and add docs for others on how to use it.
