### ISSUE TITLE
action use not found

### ISSUE THREAD

**Issue by fmigneault** [boyney123/github-actions#65]
I'm suddenly getting a error related to `CySeq/gitcret@v2` as referenced by https://github.com/boyney123/github-actions/blob/e088c488c1aa9e44ea41a08f4de8ad621d1765b7/src/actions/gitcret.md

The error in question: 
https://github.com/crim-ca/weaver/pull/74/checks?check_run_id=432780721

Do you have an idea to what happened to CySeq/gitcret? 
I get 404 from it now: https://github.com/CySeq/gitcret

**Comment by y-mehta** [comment]
Hi @fmigneault , We have fixed the issue and repo is back. 

Please re-run the workflow and let me know if you are facing any issues.

**Comment by fmigneault** [comment]
All working as before, thanks.
